"""Pydantic schemas for Tianshu Bridge API.

Mirrors Recall Sticker's chrome.storage card schema (see
~/Documents/trae_projects/recall-sticker/Recall-Sticker/content.js:49-56):
    { text, prefix, suffix, context, timestamp, sourceUrl }

Adds tianshu-specific fields: id (generated by curator), tags (extended).
"""

from typing import Literal

from pydantic import BaseModel, Field


class RawCard(BaseModel):
    """A card from Recall Sticker chrome.storage.

    Recall Sticker does not store id or tags fields — id is generated
    by the curator from timestamp; tags defaults to empty list.
    """

    text: str
    prefix: str = ""
    suffix: str = ""
    context: str = ""
    sourceUrl: str
    tags: list[str] = Field(default_factory=list)
    timestamp: int
    id: str | None = None  # generated by curator from timestamp if missing


class SyncRequest(BaseModel):
    """POST /sync/recall-sticker request body."""

    trigger: Literal["manual", "auto_on_save"]
    cards: list[RawCard]
    obsidianVaultPath: str
    m2xModel: str = "MiniMax-M3"
    minimaxApiKey: str | None = None


class CuratedCard(BaseModel):
    """A card after M2.1 curation (or fallback direct write)."""

    cardId: str
    title: str
    body: str
    tags: list[str] = Field(default_factory=list)
    wikiLinks: list[str] = Field(default_factory=list)
    mergedWith: str | None = None


class SkippedCard(BaseModel):
    cardId: str
    reason: str


class CardError(BaseModel):
    cardId: str
    message: str


class SyncResponse(BaseModel):
    """POST /sync/recall-sticker response body."""

    success: bool
    curated: list[CuratedCard] = Field(default_factory=list)
    skipped: list[SkippedCard] = Field(default_factory=list)
    errors: list[CardError] = Field(default_factory=list)
    durationMs: int = 0
    obsidianFilesWritten: list[str] = Field(default_factory=list)